# Create deployment named nginx-deployment with nginx:1.20 image with 3 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deploy-container
        image: nginx:1.20
        ports:
        - containerPort: 8084