apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-frontend
  template:
    metadata:
      labels:
        app: httpd-frontend
  spec:
    ontainers:
      - name: httpd-frontend-container
        image: httpd:2.4-alpine
        ports:
        - containerPort: 8080
