# Imagine you have a web application that occasionally hangs because of memory leaks. 
# How would you configure a liveness probe to restart the pod automatically when this occurs?

apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness
  labels: 
    test: liveness
spec: 
  containers:
    - name: liveness-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
        failureThreshold: 3   #specifies the number of times the probe will try before restart 