# Create a new pod nginx-3 with nginx image and add all env variables from from configmap map db-config-1

apiVersion: v1
kind: Config
metadata:
  name: nginx-3-configmap
data:
  DB_HOST: db.example.com
  DB_USER: development
  DB_PASSWD: password

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
spec: 
  containers:
    - name: nginx-3-container
      image: nginx
      envFrom:
        - configMapRef:
            name: nginx-3-configmap
