# Create a role binding sample-sa-pods-read-role-binding binding service account sample-sa and role pods-read
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-sa-pods-read-role-binding

  namespace: default
subjects:
- kind: ServiceAccount
  name: sample-sa # Name is case sensitive
  namespace: default
roleRef:
  kind: Role
  name: pods-read
  apiGroup: rbac.authorization.k8s.io