
# Create the role pods-read to get, create, list and delete pods in the default namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-role
  namespace: default
rules:
- apiGroups:
  - ""       #indicates the core api group 
  resources:
  - pods
  verbs:
  - get
  - create
  - list
  - delete