# simple pod that uses an emptyDir volume:

apiVersion: v1
kind: Pod
metadata:
  name: pod01
spec:
  containers:
    - image: nginx
      name: pod01-container
      volumeMounts:
        - name: cache-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: cache-volume
      emptyDir: {}